### ISSUE TITLE
Feature Request - Can the steady state hypothesis report in detail on unmatched state?

### ISSUE THREAD

**Issue by museadmin** [chaostoolkit/chaostoolkit#111]
At the moment the framework reports that the steady state has not been met, but doesn't tell you what the returned state was. e.g. 

"Steady state probe 'running-instances' is not in the given tolerance so failing this experiment"

This makes it very difficult for newcomers to establish what the tolerance should be. 

So for example the docs for the AWS project give this example:

{
  "type": "probe",
  "name": "instance-state",
  "provider": {
    "func": "instance_state",
    "type": "python",
    "arguments": {
      "state": ""
    },
    "module": "chaosaws.ec2.probes"
  }
}

Gives the error - hypothesis probe must have a tolerance entry

but we have no clue as to what a suitable tolerance would be for this and no way of seeing what it is getting back. The documentation says that the Return value is "None", while the documentation on tolerances makes no reference to handling None.

It would be very helpful if you implemented something like a unit test assertion failure message along the lines of - "expected x but got y"

**Comment by Lawouach** [comment]
Hello @museadmin,

The docs was indeed not helping as it was reporting None pretty much for everything. I have fixed it but I'm not sure saying you return a list or a dict helps fully.

It's tricky for the toolkit core to know what a probe returns exactly (I mean beyond the type like int, list, str, dict...). The structure of each probe is only known by each probe.

A long term idea would be rely on something like [pydantic](https://pydantic-docs.helpmanual.io/) so that probes could be much more verbose and precise about their output.

For now, I'm afraid, the best we can hope is to improve the documentation of the probes until we can automate a better declaration of returned values.

Does this make sense?
