### ISSUE TITLE
Control secrets access 

### ISSUE THREAD

**Issue by michael-gehtman-wix** [chaostoolkit/chaostoolkit#187]
When creating an experiment we can pass secrets based on the variable environment,
```json
  "secrets": {
    "vault": {
      "token": {
        "type": "env",
        "key": "VAULT_TOKEN_"
      },
      "address": {
        "type": "env",
        "key": "VAULT_ADDR"
      }
    }
  }
```

Now we should be able to access them in the controls (e.g. the control.py file I provided)
```json
"controls": [
    {
        "name": "tracing",
        "provider": {
            "type": "python",
            "module": "my_module.control"
        }
    }
  ]
```

The first control that is called (i.e. configure_control)
```python
def configure_control(
    configuration: Configuration = None,
    secrets: Secrets = None,
    settings: Settings = None,
    experiment: Experiment = None,
):
```
successfully converts the templates:
```json
  "token": {
    "type": "env",
    "key": "VAULT_TOKEN_"
  },
  "address": {
    "type": "env",
    "key": "VAULT_ADDR"
  }
```
 into real value. and I can access them via the `secrets` parameter.

Yet all the other controls:

- before_experiment_control
- after_experiment_control
- before_hypothesis_control
- after_hypothesis_control
- before_method_control
- after_method_control
- before_rollback_control
- after_rollback_control
- before_activity_control
- after_activity_control

have the secret parameter, but all of them get None value (it's the default value - meaning no secrets was provided)
how do we get secrets in other controls functions?
or why we don't get them?
could not find any relevant information in the [doc](https://docs.chaostoolkit.org/reference/extending/create-control-extension/)

**Comment by Lawouach** [comment]
That's an interesting question and I'm surprised you are not getting the secrets. I need to look at the code as there might be a bug.

**Comment by roeiK-wix** [comment]
Is there any progress regarding that issue?

**Comment by Lawouach** [comment]
Right, aftre some digging. I realised why you were getting no values.

Unlike the `configure_control` which always gets the secrets, as mentioned, the others need to declare which ones they are interested in in the `secrets` key of the `provider`. Like you do for actions and probes. Just declaring the function signature is not enough.

So we have the following options:

* we align the `configure_control` with the others and you will only get the secrets you declared your control was ready to consume (like actions/probes)
* we align the other control hooks with `configure_control` and you always get all secrets declared in the experiment.

Considering the power of controls one could argue option 2. is best because they need to be able to really impact all things of the experiment at any time. But from a security perspective, that means any control will always access all secrets at all times. Not sure this causes a real issue because, honestly you can access them through experiment probably anyway.

I need to think about it over the weekend.

**Comment by Lawouach** [comment]
The docs will eventually reflect whichever we go for as well.

**Comment by Lawouach** [comment]
Feel free to try to install chaostoolkit-lib master branch and try before I cut a release?

**Comment by michael-gehtman-wix** [comment]
sure, ill check it out ASAP, thank you very much.

**Comment by michael-gehtman-wix** [comment]
@Lawouach ok so I did some small experiment and debugged it.
As far as I know, all control's hooks are getting the secrets from the env (in my case).
I hope my check covers it 😄.
Thank you very much for the quick attention to this issue, Good job!
