### ISSUE TITLE
Make experiment configuration namespace scoped and reference-able by probes and actions

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#40]
Similar behaviour as is currently implemented for secrets

**Comment by russmiles** [comment]
Enable and document this as the _recommended_ approach.
Optionally add a warning to the log on detection of unscoped configuration items.

**Comment by Lawouach** [comment]
I'm finding myself questioning still this issue. I can't recall it being raised once and this sounds like changes the actual behavior for little reward.

The configuration is flat because it contains non-sensitive data which means they can be populated to all activities whereas secrets can benefit from a little scoping.

Is this actually needed Russ?

**Comment by valeriap** [comment]
@Lawouach 
I would use a probe twice within the same experiment with different configuration. 
I haven't found a way to do it with current behaviour. It would be easy with this change.

**Comment by Lawouach** [comment]
Hey, that is true. It can't be done right now indeed.
