### ISSUE TITLE
Ask for permission before running an experiment 

### ISSUE THREAD

**Issue by dastergon** [chaostoolkit/chaostoolkit#50]
When I run an experiment with `chaos run experiment.json`, it would be better if the tool showed me a prompt to verify if I would like to proceed with the experiment or not. An extra flag `--y` or --no-verification` could be also implemented to skip that step.

**Comment by Lawouach** [comment]
I see where you are coming from but I'm not sure about this one. I can appreciate that you would want safety in your particular case. But in general, when I run a command, I expect it to run, not ask me my permission again. So I'm not really in favour of such a default. I would rather have a flag that ask for my permission, not the opposite.

**Comment by dastergon** [comment]
A flag `--ask` works for me.

**Comment by buderre** [comment]
How shall the *--ask* flag work? Ask the user for every action that will be executed?

**Comment by lindybrandon** [comment]
We actually have an approval workflow that requires sign-off from the application owner. This allows for flexibility when you have a situation where the team running the experiment is not actually the same as the team that owns the application (and hence, the support and outage impact). It also allows you to request approval from teams that are upstream or downstream of the affected failure point. 

So, I do think having the ability to get sign-off is important but I don't think it should be too simplistic so that it isn't useful in all the diff use cases.

**Comment by Lawouach** [comment]
Interesting @lindybrandon. I didn't initially assume the request for a full sign-off permission from the CLI, but this is actually request. Almost, like a distinct `--sign-off <username/email>` flag for the CLI. Similar to the one from git perhaps?

**Comment by Lawouach** [comment]
@buderre It's a good question. I initially assumed it would ask once at the beginning, something like "Do you want to proceed?" but this might be too simplistic?

**Comment by lindybrandon** [comment]
that's right. Our requirement is that each disruption in an experiment has sign-off before the experiment can be fully executed. If there is a disruption that hasn't been approved, the rest will run without that one unless the experiment designates that it's all or nothing.

**Comment by Lawouach** [comment]
I see. So, the sign-off is per-activity (disruption), not global to the experiment. I think, I'd like a different issue for the sign-off altogether @lindybrandon so we can iron it out properly and perhaps update the spec to support it.

**Comment by lindybrandon** [comment]
got it. will open a new issue - we can talk about it in more depth when we see each other in January
