### ISSUE TITLE
Change wording on a chaos experiment execution that finds a weakness from "failed" to "complete"

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#56]
At the moment, if a weakness is discovered the command line output states:

```
[2018-04-27 17:36:38 INFO] Experiment ended with status: failed
```

This is confusing as the experiument has not failed, in fact it's been successful in finding a weakness, but when this experiment is run "as a test" the tested conditions of the steady-state hypothesis have failed.

Suggest changing to "

```
[2018-04-27 17:36:38 INFO] Experiment ended with status: completed
[2018-04-27 17:36:38 INFO] Steady-state hypothesis discovered weaknesses
```

Or something similar in this case.

**Comment by Lawouach** [comment]
This should be discussed as part of the API I think http://chaostoolkit.org/reference/api/journal/#format

**Comment by ksolie** [comment]
Will this affect how the notifications work? I'm assuming there will need to be a change to the event filter to something like `run-weakness` instead of `run-failure`

**Comment by Lawouach** [comment]
Hey @ksolie, that's a good catch.

I'm tempted to consider the wording @russmiles is considering to be about the narrative of the log output. Event wise, I'm not sure we can emit an event that says "weakness found", but certainly something saying "didn't go according to plan" which I thought failed would convey better.

thoughts?

**Comment by ksolie** [comment]
After looking at it closer I agree with you

**Comment by Lawouach** [comment]
We have been talking about this and we have settled for "deviated" rather than "failed".

Looking at the code, there is a risk of breaking compatibility here. The displayed text comes from the status we set in the journal. While we could add a if-statement when we are ine "failed" mode so that we display "deviated" instead (not pretty but easy enough). We would also change the wording entirely in the journal but there is a risk that we start confusing downstreams when they anticipated failed and we return deviated (vice versa).

So my take is to remain simple here and we can enhance our specification in the future to accomodate those differences.

**Comment by Lawouach** [comment]
Hey @ksolie, would you mind having a look at the following PRs as well please, since you were interested in this issue:

https://github.com/chaostoolkit/chaostoolkit-lib/pull/56
https://github.com/chaostoolkit/chaostoolkit/pull/78

Cheers

**Comment by Lawouach** [comment]
I think the changes are backwrad compatible and are only additive.

**Comment by Lawouach** [comment]
Thanks!
