### ISSUE TITLE
Add 'info' command to list current setup and status

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#64]
Also could be overloaded to suggest plugins that are indexed by the Hub?

**Comment by russmiles** [comment]
Setup information, by default, will include:
* Version of Chaos Toolkit
* CLI Plugins and versions installed.
* Drivers and versions installed.
* Current contents of the configuration (found in ~/.chaostoolkit)

Add options to select only the information you are interest in:
* `chaos info plugins` - list out just the installed CLI plugins and their versions.
* `chaos info drivers` - list out just the installed drivers and their versions.
* `chaos info config` - list out the current configuration (found in ~/.chaostoolkit)

**Comment by russmiles** [comment]
Also adding "Contribute" section to README for this project.

**Comment by Lawouach** [comment]
As I was creating the bundler yesterday, I realised how useful this command would be. Indeed a bundle can quickly become out of sync with existing driver versions. It would be handy to have this command to inspect what's available.

https://github.com/chaostoolkit/chaostoolkit-bundler

**Comment by Lawouach** [comment]
I've started working on this issue and it's not as easy as it looks.

Right now, there is no piece of information that we can lookup that tells us what extensions are installed, nor which category they fall into. We can only iterate over which packages are installed in the virtual environment but there is no metadata we can read to make sense of.

At best, we could have: `chaos info extensions` which could list all packages starting with `chaos` in their name. But even that is flaky if you have an extension that uses a different prefix. I guess it's a start.

We can't set a [Python trove classifier](https://pypi.org/pypi?%3Aaction=list_classifiers) for our needs because we can't extend the official list :/

**Comment by Lawouach** [comment]
Released in 0.17.0
