### ISSUE TITLE
use 'probe' outputs in 'actions'

### ISSUE THREAD

**Issue by 0rc** [chaostoolkit/chaostoolkit#70]
Hi guys,

As far as I can understand the general workflow of the tool is:
* check steady state hypothesis
* run actions
* check steady state hypothesis again

In this flow `probes` represent steady state hypothesis and are not used for anything else.

For the use cases I see it would be extremely useful to use outputs of 'probes' as parameters to actions and have some conditional logic in between.

Example use case:
Having hundreds of instances in AWS Region/AZ I don't want to mess up with all of them as some instances/ASGs are not built for HA. So, I want to filter ASGs that:
* match certain tags (easy)
* have more than X healthy instances registered to load balancer and serving traffic (not so easy)
* pass resulting list of ASGs to `action` so that it will operate with this subset of instances choosing random ones to stop

I cam imagine doing all the checks necessary in `action` itself but this will lead to code duplication as I can see some of checks I'd like to do in `probes` already and naturally want to reuse existing code.

Regarding conditional logic (like, don't stop instances in ASG if it has less than 2 healthy instances), do you think it is possible to integrate this to experiment yaml/json or the best place for this is action itself and one could pass conditions as parameters to `action`?

Please let me know your thoughts on this subject.

**Comment by russmiles** [comment]
This is a very important topic @0rc , thanks for bringing it up!

We've erred on the side of keeping the specification simple, and making the probes and actions as numerous and/or complex as they need to be. So that would suggest an approach where if such conditional logic is necessary then a new custom action could be implemented (either in the "official" module for a project in open source, or even as an in-house module just for a particular organisation and so not generally accessible or open sourced).

One clarification here is that we _do_ see probes being used in experimental methods (i.e. outside of the steady-state hypothesis specification) where additional information is being sourced and added to the journal _during_ the experiment's execution. You can't use this to conditionally control execution of actions or probes, but it is quite common to enrich the journal with this sort of information.

**Comment by russmiles** [comment]
Me preference at the moment is to keep the flow of the experiment's execution as simple and predictable as possible, which is what it is at the moment. The "intelligence" is in the actions and probes, custom/specific/open source, whether implemented as python modules, http endpoint invocations or independent processes.

**Comment by 0rc** [comment]
Understandable position.

But the downsides of this decision might be significant.

If probes (or whatever you call that) could be easily combined into conditions/loops inside experiment json/yaml somehow it would greatly increase flexibility, the level of code reuse and the ease of contribution.
If I can implement simple probes/checks/whatever that can be easily combined with existing probes/checks I am more likely to contribute my code back. 
If I have to implement all the logic I need in `action` than I have less reasons to contribute this back and even if I do so my contribution would be of less value to the community as my action with all the logic represents the specific use case I have. In this case those who have similar use case would just create their own action based on my code and produce more code duplication.

From my perspective this is basically the mistake other projects did (see terraform issues with conditionals/loops and hard time they are having with fixing this as a great example of similar issue)

**Comment by russmiles** [comment]
I can certainly see the downsides, and this could be just the rationale and timing to make this jump in the responsibilities of the experiment specification.

One concern I have is this would likely incur the need to have more programmatic inspection on the responses from probes etc, such as extracting a key variable and using that as something that is passed to an action. This would require some sort of expression language being added, and I've seen this be fine for very simple cases but a real debug nightmare for more complex cases.

There is possibly a better way. _Maybe_ there could be scope for, in those cases where advanced usage goes beyond the remit of the JSON experiment definition then API-level usage of the Chaos Toolkit's library might be better from a debuggable, full python program. It's an extreme step, but an option.

There's probably a half-way house here where smaller, reusable probes and actions are still encouraged with minimal conditional power in the experiment specification format. Worth exploring in some pseudo examples perhaps.

**Comment by 0rc** [comment]
Creating small python program leveraging Chaos Toolkit's library might be a good option for now, I am going to take a look at this.

Thanks.

**Comment by Lawouach** [comment]
Linking to https://github.com/chaostoolkit/chaostoolkit-lib/issues/44

**Comment by Lawouach** [comment]
Also https://github.com/chaostoolkit/chaostoolkit/issues/63

**Comment by Lawouach** [comment]
Hey folks,

Thank you @0rc for the awesome proposal. I think it certainly echoes what others have suggested in the past.

Russ and I knew initially we would need to explore one model along with the community so that the "right" approach would gradually emerge. Using a very declarative, sequential, model was a great starting point for its simplicity and ease to be understood and tried in various ways. I think it's fair to say, Russ and I aren't surprised it could evolve :)

I see at least two features here:

* Being able to propagate generated/pulled data
* Offering more control inside the declaration

While the former is needed for the latter, I believe they can be both considered (and added) for their own merits. 

My gut feeling, for now, is that the former is a great step forward. I'm almost tempted to say it could be included in 1.0 should we find the right format.

On the other hand, providing more control to the declaration requires careful thinking. As soon as we'll add something, we may have to go all the way of a full blown language and I'm a little afraid of where that could lead us.

So, I am not advert of adding pattern matching and stop conditions but it would be great if we could keep some declarative level (rather than imperative style). For instance, if we could declare "guards" much like we declare "pauses", that would have my favour.

At least for now.
