### ISSUE TITLE
Establish a Chaos Toolkit (and associated projects) open source community Code of Conduct

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit#82]
At the moment we don't have a Code of Conduct around the Chaos Toolkit (and related) open source projects. I would like to propose that we consider something similar to the following from the Debian community:

https://www.debian.org/code_of_conduct

**Comment by russmiles** [comment]
I'd like to propose additional sections such as:

- Be patient
- Be kind

**Comment by russmiles** [comment]
Maybe also:

* Be aware of cultural differences (and timezones)

**Comment by pravarag** [comment]
Was this implemented?

**Comment by Lawouach** [comment]
Good question. Unfortunately, it wasn't so far. But we are keen on the community's advice on this one! :)

**Comment by pravarag** [comment]
I can work on devising one here. Can submit a PR on the same, suggestions for enhancement will be worked upon then. How about that?

**Comment by Lawouach** [comment]
Sounds great.

**Comment by pravarag** [comment]
Cool. @Lawouach what are your thoughts on using 'Contributor Covenant Code of Conduct' ? That one is pretty universal and applicable to all.

**Comment by Lawouach** [comment]
Thanks for asking.

I tend to favour the Debian one is shorter and simpler for anyone to appreciate and abide to. The one you mentioned seems to be more about improving diversity and ensuring there is a framework to deal with that specific issue. A worthy goal but I find it to be slightly distinct from a regular code of conduct that ensures the community plays nice basically.

The debian one (or Ubuntu for a more comprehensive one) is more attractive to me because it treats the community with a positive intent on acting appropriately as adults towards the project and other members. It's closer to the philosophy of the project as a code of conduct IMO.

**Comment by pravarag** [comment]
Yeah, that's correct. Debian one is quite short and more to the point.

**Comment by pravarag** [comment]
@Lawouach here, #109 
Please suggest changes

**Comment by Lawouach** [comment]
It's been merged!

Thank you @pravarag
