### ISSUE TITLE
Export metrics to Prometheus

### ISSUE THREAD

**Issue by grubert65** [chaostoolkit/chaostoolkit#91]
I would like to branch  and study a nice way to export data regarding experiments and events to a monitoring platform (usually used to graph metrics of the apps we experiment upon). As a first platform I'm considering to target Prometheus.
Before that, I need to export metadata in a more structured format than the one used for the log file, so I'm thinking of using a simple sqlite3 db with just a couple of tables to store experiments metadata and events.
A first Prometheus exporter will expose metrics collected on that db to be collected by Prometheus.

**Comment by Lawouach** [comment]
Hey @grubert65,

Well you know what, you are timely (no pun intended ;)). I am about to release this evening (I hope) extensions that show how to add these sort of things (namely tracing via Open Tracing and logging through Humio). I feel like a Prometheus extension would be fantastic and hopefully it will give you the idea on how to go on about it?

**Comment by Lawouach** [comment]
Interestingly @grubert65, if the reporter is pull-based and lives during the life of the experiment only, won't Prometheus be unhappy when the run is finished?

My take would be this:

* use a [push approach](https://prometheus.io/docs/instrumenting/pushing/) when implemented as part of the Chaos Toolkit. That can be implemented using a [control](https://docs.chaostoolkit.org/reference/extending/create-control-extension/), and therefore live inside the chaostoolkit-prometheus extension as @russmiles suggests. This is what I'll be pushing later on for tracing for instance.
* use a pull approach when implemented as part of the Chaos Platform (which I can't link to because we haven't really completed it yet). But suffice to say that the Chaos Platform will be a control-plane for managing and scheduling chaos toolkit experiment's executions. Hence it'll be a long lived service exposing an API (which we've started describing [here](https://github.com/chaostoolkit/chaoshub-tck/blob/issue%2313/chaoshubtck/chaoshubserver/chaoshubserver.yaml))

wdyt?

**Comment by grubert65** [comment]
There are strict rules on how to implement a Prometheus exporter (see https://prometheus.io/docs/instrumenting/writing_exporters/). This is the first I'm trying to implement but all exporters I've used so far relied on Prometheus to call them at configured intervals. But I've to dig the docs yet, I may be wrong.

**Comment by Lawouach** [comment]
Hey,

To be fair, I'm no expert either ;)
But I can assure you we would love contributions around those lines! I'll let you explore and come back to us to continue the discussion!

Cheers :)
